### ISSUE TITLE
Bug: Cannot install in Docker

### ISSUE THREAD

**Issue by boardfish** [wrannaman/generators#10]
Dockerfile:

```Dockerfile
FROM node:lts-alpine
RUN apk add --no-cache mongodb
WORKDIR /opt/generators
COPY monkey.json /opt/generators/monkey.json
RUN npm install -g sugar-generate
RUN sugar-generate --schema monkey.json --destination /opt/generators/generated-api
RUN cd /opt/generators/generated-api/api && npm install
# RUN cd /opt/generators/generated-api/app && npm install
EXPOSE 7777
CMD cd ./generate-api/api && npm run start
```

Build logs:

```
Sending build context to Docker daemon  107.5kB
Step 1/9 : FROM node:lts-alpine
lts-alpine: Pulling from library/node
e7c96db7181b: Pull complete
bbec46749066: Pull complete
89e5cf82282d: Pull complete
5de6895db72f: Pull complete
Digest: sha256:07897ec27318d8e43cfc6b1762e7a28ed01479ba4927aca0cdff53c1de9ea6fd
Status: Downloaded newer image for node:lts-alpine
 ---> 9dfa73010b19
Step 2/9 : WORKDIR /opt/generators
 ---> Running in e0ead4eefd62
Removing intermediate container e0ead4eefd62
 ---> be50ab18bb74
Step 3/9 : COPY monkey.json /opt/generators/monkey.json
 ---> b5abd25e2336
Step 4/9 : RUN npm install -g sugar-generate
 ---> Running in 62848a96fc74
/usr/local/bin/sugar-generate -> /usr/local/lib/node_modules/sugar-generate/index.js
npm WARN eslint-plugin-react@7.14.2 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.

+ sugar-generate@0.1.5
added 60 packages from 45 contributors in 6.017s
Removing intermediate container 62848a96fc74
 ---> 8ac6d0775b0c
Step 5/9 : RUN sugar-generate --schema monkey.json --destination /opt/generators/generated-api
 ---> Running in 130bef8c5643
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './api/makeAPI'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/sugar-generate/index.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

I've checked that I'm running the same version locally (v10.6.0) and installing the same version (v0.1.5) in the container as I am on the host.

Of note is that there's a file in the folder it's looking in called `makeApi.js` (note the case). It's odd that locally, the case problem is ignored.

**Comment by wrannaman** [comment]
oh yeah, mac is case insensitive like that.
